// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalCabinet.Models;

#nullable disable

namespace PersonalCabinet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608180152_RevertPowerToInt")]
    partial class RevertPowerToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalCabinet.Models.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressRegistr")
                        .HasColumnType("text")
                        .HasColumnName("AddressRegistr");

                    b.Property<string>("ApplicantType")
                        .HasColumnType("text")
                        .HasColumnName("ApplicantType");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_number");

                    b.Property<string>("ApplicationReason")
                        .HasColumnType("text")
                        .HasColumnName("ApplicationReason");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("ContactPerson");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateSNILS")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DesignDeadline")
                        .HasColumnType("date");

                    b.Property<string>("DeviceAddress")
                        .HasColumnType("text")
                        .HasColumnName("DeviceAddress");

                    b.Property<string>("EnergyDeviceName")
                        .HasColumnType("text")
                        .HasColumnName("EnergyDeviceName");

                    b.Property<string>("ExtraData")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("FirstName");

                    b.Property<string>("GuarantyingSupplier")
                        .HasColumnType("text")
                        .HasColumnName("GuarantyingSupplier");

                    b.Property<string>("Inn")
                        .HasColumnType("text")
                        .HasColumnName("Inn");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("LastName");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("MiddleName");

                    b.Property<string>("ObjectAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_address");

                    b.Property<string>("OrganizationFullName")
                        .HasColumnType("text")
                        .HasColumnName("OrganizationFullName");

                    b.Property<string>("OrganizationShortName")
                        .HasColumnType("text")
                        .HasColumnName("OrganizationShortName");

                    b.Property<DateTime?>("PassportDate")
                        .HasColumnType("date");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text")
                        .HasColumnName("PassportNumber");

                    b.Property<string>("PassportSeries")
                        .HasColumnType("text")
                        .HasColumnName("PassportSeries");

                    b.Property<string>("PassportWhoIssued")
                        .HasColumnType("text")
                        .HasColumnName("PassportWhoIssued");

                    b.Property<string>("PaymentPlan")
                        .HasColumnType("text")
                        .HasColumnName("PaymentPlan");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<int?>("PreviousPowerKw")
                        .HasColumnType("integer")
                        .HasColumnName("PreviousPowerKw");

                    b.Property<string>("ReliabilityCategory")
                        .HasColumnType("text")
                        .HasColumnName("ReliabilityCategory");

                    b.Property<int?>("RequestedPower")
                        .HasColumnType("integer")
                        .HasColumnName("requested_power");

                    b.Property<string>("ResidenceAddress")
                        .HasColumnType("text")
                        .HasColumnName("ResidenceAddress");

                    b.Property<long?>("SNILS")
                        .HasColumnType("bigint")
                        .HasColumnName("SNILS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NEW'::character varying");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TotalPowerKw")
                        .HasColumnType("integer")
                        .HasColumnName("TotalPowerKw");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("applications_pkey");

                    b.HasIndex(new[] { "ApplicationNumber" }, "applications_application_number_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "idx_applications_user_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.ApplicationStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<long?>("ChangedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("old_status");

                    b.HasKey("Id")
                        .HasName("application_status_history_pkey");

                    b.HasIndex("ChangedBy");

                    b.HasIndex(new[] { "ApplicationId" }, "idx_status_history_application_id");

                    b.ToTable("application_status_history", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<long?>("DocumentTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_type_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("documents_pkey");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "ApplicationId" }, "idx_documents_application_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.DocumentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("document_types_pkey");

                    b.HasIndex(new[] { "Code" }, "document_types_code_key")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.IndividualProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("individual_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "individual_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("individual_profiles", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.HasKey("Id")
                        .HasName("messages_pkey");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ApplicationId" }, "idx_messages_application_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.OrganizationProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_person");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("short_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("organization_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "organization_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("organization_profiles", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'USER'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PersonalCabinet.Models.UserPersonalData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime?>("PassportDate")
                        .HasColumnType("date");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("ResidenceAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPersonalData");
                });

            modelBuilder.Entity("PersonalCabinet.Models.Application", b =>
                {
                    b.HasOne("PersonalCabinet.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinet.Models.ApplicationStatusHistory", b =>
                {
                    b.HasOne("PersonalCabinet.Models.Application", "Application")
                        .WithMany("ApplicationStatusHistories")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_status_history_application_id_fkey");

                    b.HasOne("PersonalCabinet.Models.User", "ChangedByNavigation")
                        .WithMany("ApplicationStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("application_status_history_changed_by_fkey");

                    b.Navigation("Application");

                    b.Navigation("ChangedByNavigation");
                });

            modelBuilder.Entity("PersonalCabinet.Models.Document", b =>
                {
                    b.HasOne("PersonalCabinet.Models.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("documents_application_id_fkey");

                    b.HasOne("PersonalCabinet.Models.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("documents_document_type_id_fkey");

                    b.HasOne("PersonalCabinet.Models.User", "UploadedByNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("documents_uploaded_by_fkey");

                    b.Navigation("Application");

                    b.Navigation("DocumentType");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("PersonalCabinet.Models.IndividualProfile", b =>
                {
                    b.HasOne("PersonalCabinet.Models.User", "User")
                        .WithOne("IndividualProfile")
                        .HasForeignKey("PersonalCabinet.Models.IndividualProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("individual_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinet.Models.Message", b =>
                {
                    b.HasOne("PersonalCabinet.Models.Application", "Application")
                        .WithMany("Messages")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("messages_application_id_fkey");

                    b.HasOne("PersonalCabinet.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("messages_sender_id_fkey");

                    b.Navigation("Application");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PersonalCabinet.Models.OrganizationProfile", b =>
                {
                    b.HasOne("PersonalCabinet.Models.User", "User")
                        .WithOne("OrganizationProfile")
                        .HasForeignKey("PersonalCabinet.Models.OrganizationProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("organization_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinet.Models.UserPersonalData", b =>
                {
                    b.HasOne("PersonalCabinet.Models.User", "User")
                        .WithOne("PersonalData")
                        .HasForeignKey("PersonalCabinet.Models.UserPersonalData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalCabinet.Models.Application", b =>
                {
                    b.Navigation("ApplicationStatusHistories");

                    b.Navigation("Documents");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PersonalCabinet.Models.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PersonalCabinet.Models.User", b =>
                {
                    b.Navigation("ApplicationStatusHistories");

                    b.Navigation("Applications");

                    b.Navigation("Documents");

                    b.Navigation("IndividualProfile");

                    b.Navigation("Messages");

                    b.Navigation("OrganizationProfile");

                    b.Navigation("PersonalData");
                });
#pragma warning restore 612, 618
        }
    }
}
